[run]
preload = ["./plugins/bunBundleDev.ts"]

[define]
"MACRO.VERSION" = '"1.44.3"'
"MACRO.BUILD_TIME" = '""'
"MACRO.PACKAGE_URL" = '"ur-agent"'
"MACRO.NATIVE_PACKAGE_URL" = 'undefined'
"MACRO.FEEDBACK_CHANNEL" = '"https://github.com/Maitham16/UR/issues"'
"MACRO.ISSUES_EXPLAINER" = '"file an issue at https://github.com/Maitham16/UR/issues"'
"MACRO.VERSION_CHANGELOG" = '""'
