import {
  chmodSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from 'node:fs'
import { join } from 'node:path'
import { detectProjectDna, formatDna } from '../../ur/projectDna.js'
import {
  loadRepoIndex,
  loadSymbolIndex,
  type RepoFileEntry,
} from '../../utils/codeIndex/repoIndex.js'
import { safeParseJSON } from '../../utils/json.js'

/**
 * Living repo wiki (Devin-Wiki analogue) + compact repo map.
 *
 * generateWiki composes .ur/wiki/ pages from data the agent already
 * maintains — project DNA and the code index (symbols, imports,
 * importedBy) — with a directory-walk fallback when no index exists, so it
 * works zero-config and gets richer after `ur code-index build`.
 *
 * generateRepoMap writes .ur/repo-map.md: a <=~60-line orientation map
 * (top dirs, highest in-degree files with their key symbols) that the
 * system prompt injects when present — the Aider/Cursor "repo map" pattern,
 * costing zero tokens until the user generates it.
 *
 * installPostMergeHook keeps both fresh automatically after every merge.
 */

const SKIP_DIRS = new Set([
  'node_modules', '.git', 'dist', 'build', 'coverage', '.ur', 'out',
])

function walkFiles(root: string, dir: string, out: string[], depth = 0): void {
  if (depth > 6 || out.length > 4000) return
  let entries
  try {
    entries = readdirSync(join(root, dir), { withFileTypes: true })
  } catch {
    return
  }
  for (const e of entries) {
    if (e.name.startsWith('.') || SKIP_DIRS.has(e.name)) continue
    const rel = dir ? `${dir}/${e.name}` : e.name
    if (e.isDirectory()) walkFiles(root, rel, out, depth + 1)
    else out.push(rel)
  }
}

function topLevelSummary(cwd: string): string[] {
  const files: string[] = []
  walkFiles(cwd, '', files)
  const byDir = new Map<string, number>()
  for (const f of files) {
    const top = f.includes('/') ? f.split('/')[0]! : '(root)'
    byDir.set(top, (byDir.get(top) ?? 0) + 1)
  }
  return [...byDir.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 15)
    .map(([d, n]) => `- \`${d}/\` — ${n} files`)
}

function keyFiles(entries: RepoFileEntry[], limit = 20): RepoFileEntry[] {
  return [...entries]
    .filter(e => e.kind === 'source')
    .sort((a, b) => (b.importedBy?.length ?? 0) - (a.importedBy?.length ?? 0))
    .slice(0, limit)
}

export function generateRepoMap(cwd: string, maxLines = 60): string {
  const lines: string[] = ['# Repo map', '']
  const index = loadRepoIndex(cwd)
  lines.push('Top-level layout:', ...topLevelSummary(cwd), '')
  if (index?.files?.length) {
    lines.push('Key files (most imported):')
    for (const f of keyFiles(index.files, 15)) {
      const symbols = (f.symbols ?? []).slice(0, 5).join(', ')
      lines.push(
        `- \`${f.path}\` ← ${f.importedBy?.length ?? 0} importers${symbols ? ` — ${symbols}` : ''}`,
      )
    }
  } else {
    lines.push(
      'Run `ur code-index build` to enrich this map with symbols and import graph.',
    )
  }
  const capped = lines.slice(0, maxLines)
  mkdirSync(join(cwd, '.ur'), { recursive: true })
  const body = `${capped.join('\n')}\n`
  writeFileSync(repoMapPath(cwd), body)
  return body
}

export function repoMapPath(cwd: string): string {
  return join(cwd, '.ur', 'repo-map.md')
}

/**
 * Compact repo map for prompt injection. Returns null (zero tokens) when no
 * map was generated, when it is stale (>7 days), or oversized.
 */
export function loadRepoMapForPrompt(cwd: string, maxBytes = 4000): string | null {
  const path = repoMapPath(cwd)
  if (!existsSync(path)) return null
  try {
    const age = Date.now() - statSync(path).mtimeMs
    if (age > 7 * 24 * 3600 * 1000) return null
    const body = readFileSync(path, 'utf-8')
    return body.length <= maxBytes ? body : `${body.slice(0, maxBytes)}\n… [map truncated]`
  } catch {
    return null
  }
}

export function wikiDir(cwd: string): string {
  return join(cwd, '.ur', 'wiki')
}

export function generateWiki(cwd: string): { pages: string[]; dir: string } {
  const dir = wikiDir(cwd)
  mkdirSync(dir, { recursive: true })
  const dna = detectProjectDna(cwd)
  const index = loadRepoIndex(cwd)
  const symbols = loadSymbolIndex(cwd)
  const stamp = new Date().toISOString()
  const pages: string[] = []

  const pkg = existsSync(join(cwd, 'package.json'))
    ? (safeParseJSON(readFileSync(join(cwd, 'package.json'), 'utf-8'), false) as {
        name?: string
        description?: string
        scripts?: Record<string, string>
      } | null)
    : null

  const indexMd = [
    `# ${pkg?.name ?? 'Project'} wiki`,
    '',
    `_Auto-generated by \`ur wiki generate\` — ${stamp}. Regenerates on merge when the hook is installed._`,
    '',
    pkg?.description ?? '',
    '',
    '## Project DNA',
    '',
    formatDna(dna),
    '',
    '## Layout',
    '',
    ...topLevelSummary(cwd),
    '',
    pkg?.scripts
      ? ['## Scripts', '', ...Object.entries(pkg.scripts).slice(0, 20).map(([k, v]) => `- \`${k}\` → \`${v}\``)].join('\n')
      : '',
    '',
    'Pages: [architecture](architecture.md) · [dependencies](dependencies.md)',
  ].join('\n')
  writeFileSync(join(dir, 'index.md'), `${indexMd}\n`)
  pages.push('index.md')

  const arch = ['# Architecture', '', `_Generated ${stamp}_`, '']
  if (index?.files?.length) {
    arch.push('## Key files (by import in-degree)', '')
    for (const f of keyFiles(index.files, 30)) {
      arch.push(`### \`${f.path}\``)
      arch.push(`Imported by ${f.importedBy?.length ?? 0} files.`)
      if (f.symbols?.length) arch.push(`Symbols: ${f.symbols.slice(0, 12).join(', ')}`)
      arch.push('')
    }
  } else {
    arch.push('No code index found. Run `ur code-index build` for file-level detail.')
  }
  if (symbols?.symbols?.length) {
    const byKind = new Map<string, number>()
    for (const s of symbols.symbols) byKind.set(s.kind, (byKind.get(s.kind) ?? 0) + 1)
    arch.push('## Symbol census', '', ...[...byKind.entries()].map(([k, n]) => `- ${k}: ${n}`))
  }
  writeFileSync(join(dir, 'architecture.md'), `${arch.join('\n')}\n`)
  pages.push('architecture.md')

  const deps = ['# Dependency map', '', `_Generated ${stamp}_`, '']
  if (index?.files?.length) {
    deps.push('| file | imports | imported by |', '|---|---|---|')
    for (const f of keyFiles(index.files, 40)) {
      deps.push(`| \`${f.path}\` | ${f.imports?.length ?? 0} | ${f.importedBy?.length ?? 0} |`)
    }
  } else {
    deps.push('No code index found — run `ur code-index build` first.')
  }
  writeFileSync(join(dir, 'dependencies.md'), `${deps.join('\n')}\n`)
  pages.push('dependencies.md')

  // Keep the prompt-injected repo map in sync with the wiki.
  generateRepoMap(cwd)

  return { pages, dir }
}

/** post-merge hook so the wiki + repo map refresh themselves after merges. */
export function installPostMergeHook(cwd: string): string | null {
  const hooksDir = join(cwd, '.git', 'hooks')
  if (!existsSync(hooksDir)) return null
  const hookPath = join(hooksDir, 'post-merge')
  const marker = '# ur-wiki-refresh'
  const line = `ur wiki generate --quiet >/dev/null 2>&1 || true ${marker}`
  const existing = existsSync(hookPath) ? readFileSync(hookPath, 'utf-8') : '#!/bin/sh\n'
  if (existing.includes(marker)) return hookPath
  writeFileSync(hookPath, `${existing.trimEnd()}\n${line}\n`)
  chmodSync(hookPath, 0o755)
  return hookPath
}
